---
title: "Topic Coherence"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Topic Coherence}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

reticulate::use_virtualenv("../env", required = TRUE)
```

Create a model and evaluate its coherence. Below we use example datasets, see [preprocessing vignette](/articles/preprocessing) to see how to obtain those.

```{r}
library(gensimr)

# Example data
corp <- common_corpus(to_r = FALSE)
dict <- common_dictionary(to_r = FALSE)

model <- model_lda(corp, num_topics = 5L, id2word = dict)

cm <- topic_coherence(model, corpus = common_corpus(), coherence = 'u_mass')
cm$get_coherence()
```

Create __multiple__ models and evaluate their coherence.

```{r}
model2 <- model_lda(corp, num_topics = 2L, id2word = dict, passes = 200L) # 3 topics
model5 <- model_lda(corp, num_topics = 5L, id2word = dict, passes = 200L) # 5 topics

models <- c(model2, model5)

cm <- topic_coherence(models, common_dictionary(), corpus = common_corpus(), coherence = 'u_mass')
cm$compare_models(models)
```
